version: "3.7"

volumes:
  prometheus_data: { }

services:

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  sendgrid-stats-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9154:9154"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:9154/-/healthy"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      DISABLE_EXPORTER_METRICS: "true"
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_USER_NAME: ${SENDGRID_USER_NAME}
      SENDGRID_API_BASE: ${SENDGRID_API_BASE:-https://api.sendgrid.com}
      SENDGRID_INCLUDE_SUBUSERS: ${SENDGRID_INCLUDE_SUBUSERS:-false}
