---
version: 2.1

orbs:
  go: circleci/go@3.0.4

workflows:
  integration:
    jobs:
      - go_build
      - docker_build
      - docker_build_and_push:
          context: "DockerHub"
          filters:
            tags:
              only: /^.*/
            branches:
              ignore:
                - /^.*/

jobs:
  go_build:
    executor:
      name: go/default
      tag: "1.26"
    steps:
      - checkout
      - go/mod-download
      - run:
          name: Enforce Go Formatted Code
          command: test -z "$(gofmt -l .)"
      - run:
          name: Install GolangCI-Lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b ./bin v2.13.2
      - run:
          name: Run GolangCI-Lint
          command: ./bin/golangci-lint run
      - run:
          name: Run tests
          command: go test ./...
      - run: make

  docker_build:
    machine:
      image: ubuntu-2404:current
    environment:
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      - run: docker version
      - run:
          name: Install buildx
          command: |
            docker buildx install
            docker run --privileged --rm tonistiigi/binfmt --install "$BUILDX_PLATFORMS"
            docker buildx create --name multi-arch --use
            docker buildx ls
      - run: make build-image-multi

  docker_build_and_push:
    machine:
      image: ubuntu-2404:current
    environment:
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      - run: docker version
      - run:
          name: Install buildx
          command: |
            docker buildx install
            docker run --privileged --rm tonistiigi/binfmt --install "$BUILDX_PLATFORMS"
            docker buildx create --name multi-arch --use
            docker buildx ls
      - run: docker login -u="${DOCKER_REGISTRY_USERNAME}" -p="${DOCKER_REGISTRY_PASSWORD}"
      - run: make build-image-multi
      - run: make push-image-multi
