replicaCount: 1

image:
  repository: chatwork/sendgrid-stats-exporter
  pullPolicy: IfNotPresent
  tag: "v0.0.10"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

serviceAnnotations: {}

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

envFrom: []
extraEnv: {}

secret:
  create: true
  name: ""
  username: ""
  apiKey: ""

service:
  type: ClusterIP
  port: 9154

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

serviceMonitor:
  enabled: false
  interval: 60s
  scrapeTimeout: 15s
  additionalLabels: {}

nodeSelector: {}

tolerations: []

affinity: {}
